var tanks = [
  'BAAA-EAA',
  'BAAB-EAA',
  'BAAC-EAA',
  'BABF-BAAA',
  'BABG-BAAA',
  'BADA-EAA',
  'BBBBG-EAA',
  'BBBDI-EAA',
  'BBBDJ-EAA',
  'BBBFH-EAA',
  'BBBFI-EAA',
  'BBBFJ-EAA',
  'BBBGA-EAA',
  'BBBGB-EAA',
  'BBBGC-EAA',
  'BBBGD-EAA',
  'BBBJB-EAA',
  'BBBJC-EAA',
  'BBCAC-EAA',
  'BBCAD-EAA',
  'BBCAE-EAA',
  'BBCIB-EAA',
  'BBCIC-EAA',
  'BBDJB-EAA',
  'BBDJC-EAA',
  'BBDJD-EAA',
  'BBDJE-EAA',
  'BBDJF-EAA',
  'BBDJG-EAA',
  'BB-EAA',
  'BBECG-EAA',
  'BBECH-EAA',
  'BBECI-EAA',
  'BBEIF-EAA',
  'BBEIG-EAA',
  'BB-FAA',
  'BBFAH-EAA',
  'BBFAI-EAA',
  'BBFD-FAA',
  'BBFH-FAA',
  'BBFI-FAA',
  'BBGBD-EAA',
  'BBGBE-EAA',
  'BBGEC-FAA',
  'BBGED-FAA',
  'BBHCH-EAA',
  'BBHCI-EAA',
  'BBIJB-EAA',
  'BBIJC-EAA',
  'BBJEG-EAA',
  'BBJEH-EAA',
  'BCADB-FAA',
  'BCADC-FAA',
  'BCCGI-EAA',
  'BCCGJ-EAA',
  'BCDJ-BAAA',
  'BC-EAA',
  'BCEI-EAA',
  'BCFD-EAA',
  'BCFE-EAA',
  'BCGD-EAA',
  'BCGE-EAA',
  'BDBCA-EAA',
  'BDBCB-EAA',
  'BDBCC-EAA',
  'BDBCD-EAA',
  'BDBCE-EAA',
  'BDBCI-EAA',
  'BDBCJ-EAA',
  'BDBDA-EAA',
  'BDBDB-EAA',
  'BDBDC-EAA',
  'BDBDD-EAA',
  'BD-EAA',
  'BDJB-EAA',
  'BDJC-EAA',
  'BDJD-EAA',
  'BDJE-EAA',
  'B-EAA',
  'BE-EAA',
  'BE-FAA',
  'B-FAA',
  'BFAD-EAA',
  'BF-EAA',
  'BF-FAA',
  'BFFA-EAA',
  'BFFB-EAA',
  'BFFC-EAA',
  'BFHI-EAA',
  'BFHJ-EAA',
  'BGBE-EAA',
  'BGBF-EAA',
  'BGCH-EAA',
  'BGCHJ-DAA',
  'BGCI-EAA',
  'BGDBA-DAA',
  'BG-EAA',
  'BG-FAA',
  'BGGD-EAA',
  'BGGE-EAA',
  'BGHE-EAA',
  'BGHF-EAA',
  'BGHG-EAA',
  'BGHJ-EAA',
  'BGIA-EAA',
  'BGIB-EAA',
  'BGJB-EAA',
  'BGJC-EAA',
  'BH-EAA',
  'BHGA-EAA',
  'BHGB-EAA',
  'BIB-EAA',
  'BIC-EAA',
  'BID-EAA',
  'BI-EAA',
  'BJC-EAA',
  'BJDB-EAA',
  'BJDC-EAA',
  'BJD-EAA',
  'BJFD-EAA',
  'BJFE-EAA',
  'BJH-EAA',
  'CA-FAA',
  'CCAAFH-EAA',
  'CCAAFI-EAA',
  'CCAAFJ-EAA',
  'CCAAHH-EAA',
  'CCAAHI-EAA',
  'CCAAHJ-EAA',
  'CCAAJE-EAA',
  'CCAAJF-EAA',
  'CCAAJI-EAA',
  'CCAAJJ-EAA',
  'CCABAA-EAA',
  'CCABAB-EAA',
  'CCABBE-EAA',
  'CCABBF-EAA',
  'CCABBG-EAA',
  'CCABBH-EAA',
  'CCABBI-EAA',
  'CCABBJ-EAA',
  'CCABCA-EAA',
  'CCABCB-EAA',
  'CCABCC-EAA',
  'CCABCF-EAA',
  'CCABCG-EAA',
  'CCABCH-EAA',
  'CCABCI-EAA',
  'CCABCJ-EAA',
  'CCABEF-EAA',
  'CC-FAA',
  'CDDC-EAA',
  'CDDD-EAA',
  'CD-FAA',
  'C-EAA',
  'CE-FAA',
  'CEIGGF-EAA',
  'CEIGGG-EAA',
  'CEIGIC-EAA',
  'CEIGID-EAA',
  'CEI-HAA',
  'CEIIBE-EAA',
  'CEIIBF-EAA',
  'CEIIBG-EAA',
  'CEIIBH-EAA',
  'CEJ-HAA',
  'C-FAA',
  'CF-FAA',
  'CG-FAA',
  'DAHG-BAAA',
  'DAHH-BAAA',
  'DBHF-BAAA',
  'DDAG-DAA',
  'DDAH-DAA',
  'DDBD-FAA',
  'DDBE-FAA',
  'DDF-EAA',
  'DDG-EAA',
  'DDH-EAA',
  'D-EAA',
  'D-FAA',
  'DHBE-EAA',
  'DHBF-EAA',
  'DJHF-EAA',
  'DJHG-EAA',
  'DJJE-EAA',
  'EADB-EAA',
  'EADC-EAA',
  'EADD-EAA',
  'EADE-EAA',
  'EADG-BAAA',
  'EAFCE-EAA',
  'EAFCF-EAA',
  'EAFH-EAA',
  'EAFI-EAA',
  'EAGB-EAA',
  'EAGC-EAA',
  'EBEA-EAA',
  'EBEB-EAA',
  'ECGH-DAA',
  'ECGI-DAA',
  'ECJB-DHH',
  'ECJC-DHH',
  'ECJHJ-EAA',
  'ECJIA-EAA',
  'ECJIB-EAA',
  'EDDB-EAA',
  'EDDC-EAA',
  'E-EAA',
  'EFAC-FAA',
  'EFAD-FAA',
  'EHHIE-EAA',
  'EHHIF-EAA',
  'EHHIG-EAA',
  'FAFA-DAA',
  'FAGG-EAA',
  'FAGH-EAA',
  'FBFEH-EAA',
  'FBFEI-EAA',
  'FBFEJ-EAA',
  'FCHC-BAAA',
  'FCHD-BAAA',
  'FCHF-EAA',
  'FCIA-BAAA',
  'FCID-BAAA',
  'FCIE-BAAA',
  'FDBD-HAA',
  'FDBE-HAA',
  'FDCJ-BAAA',
  'F-EAA',
  'FEAE-EAA',
  'FEAF-EAA',
  'FEBF-FAA',
  'FEBG-FAA',
  'FEF-EAA',
  'FEH-EAA',
  'FFAB-BAAA',
  'FFAC-BAAA',
  'FGBC-EAA',
  'FGBD-EAA',
  'FHAEH-EAA',
  'FHGJ-FAA',
  'FHHA-FAA',
  'FHHC-FAA',
  'FJEH-DAA',
  'FJEI-DAA',
  'FJFH-EAA',
  'FJFI-EAA',
  'FJHF-DAA',
  'FJHG-DAA',
  'GACB-EAA',
  'GACC-EAA',
  'GAD-DAA',
  'GAE-DAA',
  'GAGI-EAA',
  'GAGJ-EAA',
  'GAHA-EAA',
  'GAHB-EAA',
  'GAHE-EAA',
  'GAHF-EAA',
  'G-BAAA',
  'GCHG-EAA',
  'GCHH-EAA',
  'GDAF-EAA',
  'G-EAA',
  'GECB-EAA',
  'GECC-EAA',
  'GFEH-EAA',
  'GFEI-EAA',
  'GFJI-BAAA',
  'GFJJ-BAAA',
  'GGAA-BAAA',
  'GGAB-BAAA',
  'GGAC-EAA',
  'GGAE-EAA',
  'GGAF-EAA',
  'GGBE-EAA',
  'GGBF-EAA',
  'GGBH-EAA',
  'GGBI-EAA',
  'GGED-EAA',
  'GGEE-EAA',
  'GGHE-EAA',
  'GGHF-EAA',
  'GHAF-EAA',
  'GHAG-EAA',
  'GHFJ-DAA',
  'GHGA-DAA',
  'GHGI-FAA',
  'GHHF-EAA',
  'GHJJ-FAA',
  'GIDG-EAA',
  'GIDH-EAA',
  'GIDJ-EAA',
  'GIEA-EAA',
  'GIEI-FAA',
  'GIEJ-EAA',
  'GIEJ-FAA',
  'GIFA-EAA',
  'GIGJ-FAA',
  'GIHB-FAA',
  'GIIC-FAA',
  'GJA-FAA',
  'GJCB-EAA',
  'GJCC-EAA',
  'GJEF-EAA',
  'GJEG-EAA',
  'GJJE-FAA',
  'GJJF-FAA',
  'GJJI-EAA',
  'GJJJ-EAA',
  'HAAD-EAA',
  'HAAE-EAA',
  'HAC-FAA',
  'HAFD-EAA',
  'HAFE-EAA',
  'HAJB-EAA',
  'HAJC-EAA',
  'HBFE-DAA',
  'HBFF-DAA',
  'HBHI-DAA',
  'HBHJ-DAA',
  'HBJA-DAA',
  'HBJB-DAA',
  'HBJD-DAA',
  'HBJE-DAA',
  'HCAH-BAAA',
  'HCCA-EAA',
  'HCCB-EAA',
  'HCEB-EAA',
  'HCEC-EAA',
  'HCG-FAA',
  'HCHE-EAA',
  'HCH-FAA',
  'HCHF-EAA',
  'HCIG-FAA',
  'HCIH-FAA',
  'HDIC-DAA',
  'HDID-DAA',
  'H-EAA',
  'HEDB-EAA',
  'HEDC-EAA',
  'HGDD-FAA',
  'HGDE-FAA',
  'HGJG-EAA',
  'HGJH-EAA',
  'HHCA-EAA',
  'HHCB-EAA',
  'HHDE-EAA',
  'HHEAJ-EAA',
  'HHEBA-EAA',
  'HHEBB-EAA',
  'HHEEI-EAA',
  'HHEEJ-EAA',
  'HHFGH-EAA',
  'HHFGI-EAA',
  'HHIG-FAA',
  'HIAEC-EAA',
  'HIAED-EAA',
  'HIBI-EAA',
  'HIBJ-EAA',
  'HICJ-EAA',
  'HJAH-BAAA',
  'HJC-FAA',
  'HJD-FAA',
  'HJE-FAA',
  'HJGF-EAA',
  'HJJI-FAA',
  'IADF-EAA',
  'IADG-EAA',
  'IAJH-FAA',
  'IAJI-FAA',
  'IBBB-EAA',
  'IBBC-EAA',
  'IBDC-BAAA',
  'IBIG-EAA',
  'IBIH-EAA',
  'ICAB-EAA',
  'ICHE-EAA',
  'IDAJ-FAA',
  'IDBA-FAA',
  'IDDC-EAA',
  'IDHF-FAA',
  'IDHG-FAA',
  'IDII-EAA',
  'I-EAA',
  'IECE-EAA',
  'IECF-EAA',
  'IECH-EAA',
  'IECI-EAA',
  'IEEC-EAA',
  'IEH-FAA',
  'IEI-FAA',
  'IGAI-FAA',
  'IGAJ-FAA',
  'IGDG-EAA',
  'IGEE-EAA',
  'IHAG-EAA',
  'IHAH-EAA',
  'IHBA-EAA',
  'IHBB-EAA',
  'IHBG-FAA',
  'IHBH-FAA',
  'IHCG-EAA',
  'IHCH-EAA',
  'IHGC-EAA',
  'IHGD-EAA',
  'IIAH-EAA',
  'IIAI-EAA',
  'IIGE-EAA',
  'IIGF-EAA',
  'IIGH-EAA',
  'IIGI-EAA',
  'IIID-EAA',
  'IIIE-EAA',
  'IJAD-EAA',
  'IJAE-EAA',
  'IJAG-EAA',
  'IJBB-EAA',
  'IJBD-EAA',
  'IJCDH-EAA',
  'IJCDI-EAA',
  'IJED-FAA',
  'IJEE-FAA',
  'IJEH-EAA',
  'IJEI-EAA',
  'IJEJ-EAA',
  'IJFA-EAA',
  'IJFB-EAA',
  'IJFC-EAA',
  'IJFF-EAA',
  'IJFJ-EAA',
  'IJGA-EAA',
  'IJGC-FAA', 
  'IJGD-FAA', 
  'IJHG-EAA',
  'IJHH-EAA',
  'IJIB-EAA',
  'IJIH-EAA',
  'IJJB-FAA',
  'IJJC-FAA',
  'IJJD-FAA',
  'IJJE-EAA',
  'IJJF-EAA',
  'JAAA-EAA',
  'JAAB-EAA',
  'JABI-EAA',
  'JABJ-EAA',
  'JADD-EAA',
  'JADE-EAA',
  'JAFI-EAA',
  'JAFJ-EAA',
  'JAGD-DAA',
  'JAGE-DAA',
  'JAIA-EAA',
  'JBEF-EAA',
  'JBEG-EAA',
  'JBFE-EAA',
  'JCIE-EAA',
  'JCJG-DIB',
  'JDBJ-EAA',
  'JDCA-EAA',
  'JDCC-EAA',
  'JEAG-FAA',
  'JECE-EAA',
  'JECF-EAA',
  'JEEA-EAA',
  'JEEB-EAA',
  'JFBE-FAA',
  'JFBF-FAA',
  'JFCG-EAA',
  'JFCH-EAA',
  'JFCJ-EAA',
  'JFDA-EAA',
  'JFEC-EAA',
  'JFGF-EAA',
  'JFGG-EAA',
  'JFHC-EAA',
  'JFIJ-EAA',
  'JFJA-EAA',
  'JGFE-EAA',
  'JGFF-EAA',
  'JIFH-EAA',
  'JIFI-EAA',
  'JIFJ-EAA',
  'JIHI-EAA',
  'JIIA-EAA',
  'JIIC-EAA',
  'JIID-EAA'
];

var locations = [
  'Barrier Pillars',
  'Barrow Height',
  'Bayspire',
  'Befogged Way',
  'Bloody Hamlet',
  'Boar Rapids',
  'Briar Dock',
  'Cane Street',
  'Charred Hollow',
  'Cork Bay',
  'Curseddingle',
  'Darken Abyss',
  'Dartville',
  'Desolate Dunes',
  'Eldritch Sea',
  'Firmbrae',
  'Flag Knoll',
  'Fume Wood',
  'Girdling Neck',
  'Glory Minster',
  'Harsh Mounds',
  'Horridland',
  'Icy Avenue',
  'Keel Glen',
  'Keystonerood',
  'Lethalbog',
  'Lightless Pale',
  'Lumpy Hostelry',
  'Omen Tavern',
  'Qualm Mire',
  'Safe Dunes',
  'Sailors Wash',
  'Shoal Head',
  'Sky Heights',
  'Slack Barrow',
  'Sleet Plateau',
  'Slimebridge',
  'Slough Mud',
  'Snowbound Chapel',
  'Solitary Arbor',
  'Squalid Fortress',
  'Stable Crags',
  'Thirsty Glen',
  'Tight City',
  'Torch Mark',
  'Torrid Gully',
  'Virgin Gulf',
  'Web Mounds',
  'Wilted Ocean'
]
var leases = [
  'Aguadilla',
  'Alhambra',
  'Aliso Viejo',
  'Anaconda',
  'Anaheim',
  'Asbury Park',
  'Auburn',
  'Auburn Hills',
  'Bakersfield',
  'Barre',
  'Bartlesville',
  'Bay City',
  'Bay St. Louis',
  'Beaumont',
  'Belpre',
  'Berkeley',
  'Billings',
  'Boston',
  'Boulder',
  'Bowling Green',
  'Bowling Green',
  'Brooklyn Park',
  'Burlingame',
  'Cairo',
  'Calabasas',
  'Cedar Rapids',
  'Charleston',
  'Charleston',
  'Charlotte Amalie',
  'Charlotte Amalie',
  'Chino Hills',
  'Cicero',
  'Clairton',
  'College Park',
  'Commerce',
  'Concord',
  'Coos Bay',
  'Coral Springs',
  'Corinth',
  'Corinth',
  'Council Bluffs',
  'Dallas',
  'Danbury',
  'Danbury',
  'Danville',
  'Downey',
  'Duarte',
  'Eatontown',
  'Effingham',
  'El Segundo',
  'Elizabeth City',
  'Elko',
  'Elsmere',
  'Enfield',
  'Erie',
  'Fairfield',
  'Fajardo',
  'Fargo',
  'Farrell',
  'Fernley',
  'Flint',
  'Fredericksburg',
  'Fremont',
  'Fremont',
  'Gary',
  'Georgetown',
  'Georgetown',
  'Grambling',
  'Grand Forks',
  'Guayanilla',
  'Hackensack',
  'Harrisburg',
  'Hastings',
  'Hazleton',
  'Henderson',
  'Hoboken',
  'Honolulu',
  'Hoover',
  'Idabel',
  'Idaho Falls',
  'Iowa City',
  'Iowa City',
  'Janesville',
  'Jenks',
  'Joliet',
  'Kent',
  'Knoxville',
  'Knoxville',
  'Kokomo',
  'La CaÃ±ada Flintridge',
  'La Palma',
  'LaGrange',
  'Laguna Woods',
  'Lake Charles',
  'Lancaster',
  'Lewiston',
  'Lima',
  'Littleton',
  'Lockport',
  'Long Beach',
  'Los Alamitos',
  'Lynwood',
  'Malden',
  'Maywood',
  'Mechanicville',
  'Memphis',
  'Meriden',
  'Meridian',
  'Meridian',
  'Mesa',
  'Miami',
  'Midland',
  'Mission Viejo',
  'Moorhead',
  'Mount Pleasant',
  'Naperville',
  'Nevada City',
  'New Brunswick',
  'New Haven',
  'New Kensington',
  'New Orleans',
  'New Rochelle',
  'Newburyport',
  'Newport',
  'Norfolk',
  'North Charleston',
  'North Platte',
  'North Platte',
  'Norton',
  'Oak Ridge',
  'Ogden',
  'Oneonta',
  'Owensboro',
  'Palos Verdes Estates',
  'Palos Verdes Estates',
  'Phoenix',
  'Plantation',
  'Pocatello',
  'Port Jervis',
  'Pulaski',
  'Rawlins',
  'Redlands',
  'Reedsport',
  'Rehoboth Beach',
  'Rensselaer',
  'Riverton',
  'Rock Springs',
  'Rockford',
  'Rockville',
  'Rocky Mount',
  'Saint Joseph',
  'Saipan',
  'Salem',
  'Salinas',
  'San Clemente',
  'San Gabriel',
  'Sandy',
  'Sandy Springs',
  'Santa Clara',
  'Santa Monica',
  'Scottsdale',
  'Scranton',
  'Seward',
  'Sharon',
  'Shreveport',
  'Sioux Falls',
  'Sister Bay',
  'Sonoma',
  'Spokane',
  'Springdale',
  'Stafford',
  'Stanton',
  'Superior',
  'Sutter Creek',
  'Tallahassee',
  'Temecula',
  'Thousand Oaks',
  'Topeka',
  'Tucson',
  'Turlock',
  'Tuscaloosa',
  'Tustin',
  'Tyler',
  'Urbana',
  'Vail',
  'Victoria',
  'Warren',
  'Warwick',
  'Waterloo',
  'Wausau',
  'Weirton',
  'Wichita',
  'Williamsburg',
  'Williamsport',
  'Wisconsin Rapids',
  'Yorba Linda',
  'York',
  'York',
  'Ypsilanti',
  'Yukon'
]